FROM python:3.7-buster

# Install dependencies
RUN apt update -y && apt upgrade -y
RUN apt update --fix-missing
RUN apt install -y libharfbuzz-dev libfribidi-dev
RUN apt update --fix-missing
RUN apt install -y r-cran-rcppeigen
RUN apt update --fix-missing
RUN apt install -y vim rsync
RUN apt update -y && apt upgrade -y
RUN apt update --fix-missing
RUN apt install -y fastqc
RUN apt install -y graphlan
RUN apt clean
RUN pip install tqdm pandas
RUN apt update -y && apt upgrade -y


#############
## Sources ##
#############
RUN mkdir base
COPY . /base
RUN /bin/bash /base/databases/SILVA_download.sh


######################
## PIP DEPENDENCIES ##
######################
RUN pip install --upgrade pip
COPY requirements.txt base/
RUN pip install --upgrade -r base/requirements.txt


######################
## R and R PACKAGES ##
######################
RUN apt update -y
RUN apt install -y r-base
# RUN Rscript base/R_packages_install.R

# Adding run_imngs2 command to PATH
RUN /bin/chmod 777 /base/run_imngs2.py
RUN /bin/ln -s /base/run_imngs2.py /usr/local/bin/run_imngs2 

WORKDIR /base
# ENTRYPOINT ["./entrypoint.sh"]
