version: '2'

services:
  tactic_pipeline:
    container_name: tactic_pipeline_cont
    build:
      context: .
      dockerfile: Dockerfile.IMNGS2Pipeline
    image: tactic_pipeline
    hostname: tactic
    command: "tail -F /base/requirements.txt"
    # volumes:
    #   - /media/adminuser/CFM/inputs:/base/inputs
    #   - /media/adminuser/MSD-Storage/databases:/base/databases
    env_file:
      - ./.env.prod
