version: '2'

services:
  cfm:
    container_name: CFM_RegSeq
    build:
      context: .
      dockerfile: Dockerfile.cfm_regseq
    hostname: CFM_RegSeq
    command: ./run_cfm_regseq.sh
    volumes:
      - /media/adminuser/CFM/inputs:/srv/cfm/inputs
      - /media/adminuser/CFM/outputs:/srv/cfm/outputs
      - /media/adminuser/MSD-Storage/databases:/srv/cfm/databases
      - /media/adminuser/imngs2/crc/docs/:/srv/cfm/docs
    env_file:
      - ./.env.prod
