FROM mpourjam/python3.7_buster_r4.3.1


###########################
# Copying necessary files #
###########################
RUN mkdir -p /base
RUN mkdir -p /base/binaries
RUN mkdir -p /base/spikesidx
RUN mkdir -p /base/databases
RUN mkdir -p /base/imngs2_pipeline
COPY binaries/ /base/binaries/
COPY spikesidx/ /base/spikesidx/
COPY databases/ /base/databases/
COPY imngs2_pipeline /base/imngs2_pipeline/
COPY run_imngs2.py /base/run_imngs2.py
COPY IMNGS2Pipeline_args.yml /base/IMNGS2Pipeline_args.yml


#########################
# Downloading Databases #
#########################
RUN /bin/bash /base/databases/SILVA_download.sh


######################
## PIP DEPENDENCIES ##
######################
RUN pip install --upgrade pip
RUN pip install --upgrade PyYAML==6.0 billiard==4.1.0


######################
## R and R PACKAGES ##
######################
RUN Rscript -e '\
library("devtools"); install_version("vegan", version="2.6-2", repos="https://cran.r-project.org");\
install_version("GUniFrac", version="1.7", repos="https://cran.r-project.org");\
install_version("ggplot2", version="3.4.2", repos="https://cran.r-project.org");\
install_version("iNEXT", version="2.0.20", repos="https://cran.r-project.org");\
'

RUN rm -rf /crc/src/

# Adding run_imngs2 command to PATH
RUN /bin/chmod 777 -R /base 
RUN /bin/ln -s /base/run_imngs2.py /usr/local/bin/run_imngs2
WORKDIR /base
