install.packages("https://cran.r-project.org/src/contrib/Archive/RcppEigen/RcppEigen_0.3.3.9.1.tar.gz", repos=NULL, type='source', dependencies=T)
install.packages("https://cran.r-project.org/src/contrib/Archive/xts/xts_0.12.1.tar.gz", repos=NULL, type='source', dependencies=T)
install.packages("https://cran.r-project.org/src/contrib/Archive/timeDate/timeDate_3043.102.tar.gz", repos=NULL, type='source', dependencies=T)
install.packages('vegan')
install.packages('GUniFrac')
install.packages('ggplot2')
install.packages('devtools')
library(devtools)
install.packages('iNEXT')